name: Test Trigger

on:
  workflow_dispatch:

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.EVALUATION_PROXY_INTEGRATION_APP_ID }}
          application_private_key: ${{ secrets.EVALUATION_PROXY_INTEGRATION_KEY }}

      - name: Trigger sdk-tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.token.outputs.token }}" \
            https://api.github.com/repos/amplitude/sdk-tests/dispatches \
            -d '{"event_type": "test-trigger", "client_payload": {"test": "ok"}}'
